spring:
  application:
    name: translationMcpWithKotlin
  profiles:
    include: secret
logging:
  level:
    com:
      mcp:
        translationmcpwithkotlin: DEBUG
    root: INFO
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: logs/translation.log
